### ISSUE TITLE
Add pydtls to PyPi, would that be an idea?

### ISSUE THREAD

**Issue by mcfreis** [rbit/pydtls#10]
As the title says, add pydtls to the Python Package Index for easy installation.

https://packaging.python.org/distributing/#uploading-your-project-to-pypi

Havn't done it myself yet, but doesn't look to complicated.

Just an idea.

**Comment by rbit** [comment]
PyDTLS has been on PyPI since the initial release: https://pypi.python.org/pypi/Dtls/1.0.1. I'll upload our most recent version soon.

**Comment by rbit** [comment]
PyPI is updated. pip install should work from Windows 32-bit and 64-bit, and from Linux.

**Comment by notedit** [comment]
so  this project is alive again.   thanks  @rbit
