### ISSUE TITLE
setup.py error in master

### ISSUE THREAD

**Issue by edmont** [rbit/pydtls#16]
It seems it comes from [Release 1.2.2](https://github.com/rbit/pydtls/commit/0d6ee12121e3e176e81d7c91ef3ee74d213c861a#diff-2eeaed663bd0d25b7e608891384b7298)

```
pydtls-master# python setup.py
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    long_description = open("README.rst").read()
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by rbit** [comment]
To install from PyPI, run `pip install Dtls`.

If you're git cloning, there is no need to install. You can run straight out of the cloned project root directory.
