### ISSUE TITLE
DTLS1.2

### ISSUE THREAD

**Issue by test12345678** [rbit/pydtls#6]
Hi,

I'm looking for an easy-to-use DTLS solution that works on windows platform. How much on an effort would it be to add support for DTLS1.2 for use on windows? It is suported starting with openssl 1.0.2a.

Regards,
Krzysztof

**Comment by rbit** [comment]
I haven't looked into it. Probably the easiest way to get this going is for you to send me a patch.

**Comment by mcfreis** [comment]
My Pull request "Added support for EC-Functions and DTLSv1.2 (Updated OpenSSL-Lib to V1.0.2j)" #7 might fix this issue.

Kind regards,
Björn

**Comment by rbit** [comment]
Merged into 1.2.0.
